# -*- coding: utf-8 -*-
"""Solution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N8f6mWgDGGa0RYSCM_BU2WFFAbpxP-ZS
"""

T = int(input().strip())

for i in range(T):
    expr = input().strip().split()
    if expr[0] == "calculate":
        expr = expr[1:]

    x1, op, x2 = expr
    x1, x2 = int(x1), int(x2)

    if op == '+':
        res = x1 + x2
    elif op == '-':
        res = x1 - x2
    elif op == '*':
        res = x1 * x2
    elif op == '/':
        res = x1 / x2

    print(f"{res:.6f}")